onboarding = false

[ui]
agent_panel_sort = "spaces"
pane_gaps = false

[keys]
prefix = "ctrl+ø"
split_vertical = "prefix+v"
split_horizontal = "prefix+-"
previous_tab = "prefix+p"
next_tab = "prefix+n"
previous_workspace = "prefix+("
next_workspace = "prefix+)"
zoom = "prefix+z"
edit_scrollback = "prefix+/"
switch_workspace = "prefix+shift+1..9"

[ui.sound]
enabled = false
