return {
  -- "folke/noice.nvim",
  -- opts = {
  --   -- add any options here
  -- },
  -- dependencies = {
  --   -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
  --   "MunifTanjim/nui.nvim",
  --   -- OPTIONAL:
  --   --   `nvim-notify` is only needed, if you want to use the notification view.
  --   --   If not available, we use `mini` as the fallback
  -- },
  -- config = function()
  --   require("noice").setup({
  --     lsp = {
  --       -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
  --       override = {
  --         ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
  --         ["vim.lsp.util.stylize_markdown"] = true,
  --         ["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
  --       },
  --     },
  --     -- you can enable a preset for easier configuration
  --     presets = {
  --       bottom_search = true, -- use a classic bottom cmdline for search
  --       command_palette = true, -- position the cmdline and popupmenu together
  --       long_message_to_split = true, -- long messages will be sent to a split
  --       inc_rename = true, -- enables an input dialog for inc-rename.nvim
  --       lsp_doc_border = true, -- add a border to hover docs and signature help
  --     },
  --     views = {
  --       cmdline = {
  --         backend = "popup",
  --         relative = "editor",
  --         position = {
  --           row = "50%",
  --           col = "10%",
  --         },
  --         size = {
  --           height = "auto",
  --           width = "100%",
  --         },
  --         border = {
  --           style = "none",
  --         },
  --         win_options = {
  --           winhighlight = {
  --             Normal = "NoiceCmdline",
  --             IncSearch = "",
  --             CurSearch = "",
  --             Search = "",
  --           },
  --         },
  --       },
  --     },
  --   })
  -- end,
}
